variable "aws_region1" {}
variable "aws_region2" {}
variable "environment" {}
variable "ProjectID" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "public_subnet_cidrs" {}
variable "azs" {}
variable "Public_Routing_Table" {}